name: SonarQube Analysis

on:
workflow_dispatch:
push:
    branches:
      - main

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: sqp_c917e435e65aae05304e8a5cddec8cae361fcc0f
          SONAR_HOST_URL: http://3.88.181.110:9000
        run: |
          mvn clean package sonar:sonar
      - name: Upload coverage report to SonarQube
        uses: sonarcloud/sonarcloud-github-action@v1
        with:
          github-token: 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
          sonar-token: sqp_c917e435e65aae05304e8a5cddec8cae361fcc0f
          sonar-host-url: http://3.88.181.110:9000
